### ISSUE TITLE
Missing wikt.mw — another take

### ISSUE THREAD

**Issue by twardoch** [kbatsuren/wiktra#3]
A simpler way to solve the missing wikt.mw problem would be to add

```
import os
os.chdir(os.path.dirname(__file__))
```

at the beginning of Wiktra.py

**Comment by kbatsuren** [comment]
I am sorry for the horrible late reply.

Thank you very much for the code, and I am afraid it is not working. The problem is that Wiktra.py sends its code into Lupa as it compiles the code and trying to find wikt.mw file. Now it is like I need to write a Lupa code to find the correct directory of the files. Do you have any other solution?

**Comment by twardoch** [comment]
I think you may have made some improvements? 

I just forked and installed wiktra, and it worked fine.

**Comment by twardoch** [comment]
I opened a small PR that addresses another problem I found. https://github.com/kbatsuren/wiktra/pull/4?w=1
